const { contextBridge, ipcRenderer } = require('electron')

// 只暴露白名单方法给渲染层，避免直接暴露 node/electron 能力（安全）。
contextBridge.exposeInMainWorld('electronAPI', {
  getCategories: () => ipcRenderer.invoke('getCategories'),
  getSubjects: () => ipcRenderer.invoke('getSubjects'),
  getCurrentSubject: () => ipcRenderer.invoke('getCurrentSubject'),
  setCurrentSubject: (id) => ipcRenderer.invoke('setCurrentSubject', id),
  getQuestions: (opts) => ipcRenderer.invoke('getQuestions', opts),
  submitAnswer: (payload) => ipcRenderer.invoke('submitAnswer', payload),
  getWrongBook: () => ipcRenderer.invoke('getWrongBook'),
  getFavorites: () => ipcRenderer.invoke('getFavorites'),
  toggleFavorite: (questionId) => ipcRenderer.invoke('toggleFavorite', questionId),
  getNote: (questionId) => ipcRenderer.invoke('getNote', questionId),
  saveNote: (payload) => ipcRenderer.invoke('saveNote', payload),
  listNotes: () => ipcRenderer.invoke('listNotes'),
  getNotedQuestionIds: () => ipcRenderer.invoke('getNotedQuestionIds'),
  getStats: () => ipcRenderer.invoke('getStats'),
  getSummary: () => ipcRenderer.invoke('getSummary'),
  getChapterProgress: (subjectId) => ipcRenderer.invoke('getChapterProgress', subjectId),
  getWeeklyTrend: () => ipcRenderer.invoke('getWeeklyTrend'),
  getMonthlyCalendar: (year, month) => ipcRenderer.invoke('getMonthlyCalendar', year, month),
  getRecentRecords: (limit) => ipcRenderer.invoke('getRecentRecords', limit),
  clearUserData: () => ipcRenderer.invoke('clearUserData'),
  exportData: () => ipcRenderer.invoke('exportData'),
  importData: (json) => ipcRenderer.invoke('importData', json),

  // 云同步（GitHub Gist）
  syncGetConfig: () => ipcRenderer.invoke('syncGetConfig'),
  syncConnect: (token) => ipcRenderer.invoke('syncConnect', token),
  syncDisconnect: () => ipcRenderer.invoke('syncDisconnect'),
  syncNow: () => ipcRenderer.invoke('syncNow'),

  // 题库管理
  listQuestions: (opts) => ipcRenderer.invoke('listQuestions', opts),
  addQuestion: (q) => ipcRenderer.invoke('addQuestion', q),
  updateQuestion: (q) => ipcRenderer.invoke('updateQuestion', q),
  deleteQuestion: (id) => ipcRenderer.invoke('deleteQuestion', id),
  importQuestionBank: (rows, opts) => ipcRenderer.invoke('importQuestionBank', rows, opts),
  getBankStats: () => ipcRenderer.invoke('getBankStats'),
  exportBank: (subjectId) => ipcRenderer.invoke('exportBank', subjectId),
  exportExcel: (subjectId) => ipcRenderer.invoke('exportExcel', subjectId),
  exportExcelTemplate: () => ipcRenderer.invoke('exportExcelTemplate'),
  addCategory: (payload) => ipcRenderer.invoke('addCategory', payload),
  renameCategory: (payload) => ipcRenderer.invoke('renameCategory', payload),
  deleteCategory: (id) => ipcRenderer.invoke('deleteCategory', id),
  // 模拟卷组卷 / 题目图片
  generatePaper: (payload) => ipcRenderer.invoke('generatePaper', payload),
  listPapers: () => ipcRenderer.invoke('listPapers'),
  getPaper: (id) => ipcRenderer.invoke('getPaper', id),
  deletePaper: (id) => ipcRenderer.invoke('deletePaper', id),
  saveImage: (buf, ext) => ipcRenderer.invoke('saveImage', buf, ext),
  getImage: (name) => ipcRenderer.invoke('getImage', name),
  // 标签 / 薄弱分析 / 相似题 / 批量操作 / 设置
  setQuestionTags: (questionId, tags) => ipcRenderer.invoke('setQuestionTags', questionId, tags),
  getQuestionTags: (questionId) => ipcRenderer.invoke('getQuestionTags', questionId),
  listTags: () => ipcRenderer.invoke('listTags'),
  getWeakChapters: (subjectId, limit) => ipcRenderer.invoke('getWeakChapters', subjectId, limit),
  getSimilarQuestions: (questionId, limit) => ipcRenderer.invoke('getSimilarQuestions', questionId, limit),
  getWeakQuestions: (limit, subjectId, categoryId) => ipcRenderer.invoke('getWeakQuestions', limit, subjectId, categoryId),
  batchUpdateQuestions: (ids, patch) => ipcRenderer.invoke('batchUpdateQuestions', ids, patch),
  batchDeleteQuestions: (ids) => ipcRenderer.invoke('batchDeleteQuestions', ids),
  getSetting: (key) => ipcRenderer.invoke('getSetting', key),
  setSetting: (key, value) => ipcRenderer.invoke('setSetting', key, value),
  getAchievements: () => ipcRenderer.invoke('getAchievements'),
  parseSheet: (buf) => ipcRenderer.invoke('parseSheet', buf),
  kbImportFiles: (paths) => ipcRenderer.invoke('kbImportFiles', paths),
  kbList: () => ipcRenderer.invoke('kbList'),
  kbGet: (id) => ipcRenderer.invoke('kbGet', id),
  kbUpdate: (id, patch) => ipcRenderer.invoke('kbUpdate', id, patch),
  kbDelete: (id) => ipcRenderer.invoke('kbDelete', id),
  kbSetTags: (docId, tags) => ipcRenderer.invoke('kbSetTags', docId, tags),
  kbTags: () => ipcRenderer.invoke('kbTags'),
  kbLink: (payload) => ipcRenderer.invoke('kbLink', payload),
  kbUnlink: (docId, questionId) => ipcRenderer.invoke('kbUnlink', docId, questionId),
  kbLinksForQuestion: (questionId) => ipcRenderer.invoke('kbLinksForQuestion', questionId),
  kbLinksForDoc: (docId) => ipcRenderer.invoke('kbLinksForDoc', docId),
  kbSearch: (query, limit) => ipcRenderer.invoke('kbSearch', query, limit),
  kbStats: () => ipcRenderer.invoke('kbStats'),
  kbRead: (id) => ipcRenderer.invoke('kbRead', id),
  kbOpen: (id) => ipcRenderer.invoke('kbOpen', id)
})
